// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_MoaXVctArUyWqsI9l36CwLr4HbG-HFA',
    appId: '1:348385625862:web:42fe7a2b4ea1542f774087',
    messagingSenderId: '348385625862',
    projectId: 'ntou-assistant',
    authDomain: 'ntou-assistant.firebaseapp.com',
    storageBucket: 'ntou-assistant.appspot.com',
    measurementId: 'G-DFWQKEG8PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwcBx-oaUKnGd9UAkU56XzjNOJC1rOgM',
    appId: '1:348385625862:android:a094260e1fe97da0774087',
    messagingSenderId: '348385625862',
    projectId: 'ntou-assistant',
    storageBucket: 'ntou-assistant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW18hSTJy3qNeJltw2luZsy-qaTL3Y26o',
    appId: '1:348385625862:ios:97a19d9330ef3f69774087',
    messagingSenderId: '348385625862',
    projectId: 'ntou-assistant',
    storageBucket: 'ntou-assistant.appspot.com',
    iosBundleId: 'com.example.ntouAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW18hSTJy3qNeJltw2luZsy-qaTL3Y26o',
    appId: '1:348385625862:ios:dbb07e71c0ab8f95774087',
    messagingSenderId: '348385625862',
    projectId: 'ntou-assistant',
    storageBucket: 'ntou-assistant.appspot.com',
    iosBundleId: 'com.example.ntouAssistant.RunnerTests',
  );
}
